export const palette = (theme) => {
  return {
    common: {
      // black: theme.colors?.darkPaper,
      dark: theme.colors?.darkPaper,
    },
    primary: {
      light: theme.colors?.primaryLight,
      main: theme.colors?.primaryMain,
      dark: theme.colors?.primaryDark,
      200: theme.colors?.primary200,
      800: theme.colors?.primary800,
    },
    secondary: {
      light: theme.colors?.secondaryLight,
      main: theme.colors?.secondaryMain,
      dark: theme.colors?.secondaryDark,
      200: theme.colors?.secondary200,
      800: theme.colors?.secondary800,
    },
    error: {
      light: theme.colors?.errorLight,
      main: theme.colors?.errorMain,
      dark: theme.colors?.errorDark,
    },
    orange: {
      light: theme.colors?.orangeLight,
      main: theme.colors?.orangeMain,
      dark: theme.colors?.orangeDark,
    },
    warning: {
      light: theme.colors?.warningLight,
      main: theme.colors?.warningMain,
      dark: theme.colors?.warningDark,
    },
    success: {
      light: theme.colors?.successLight,
      200: theme.colors?.success200,
      main: theme.colors?.successMain,
      dark: theme.colors?.successDark,
    },
    tennis: {
      light: theme.colors?.tennisLight,
      main: theme.colors?.tennisMain,
      dark: theme.colors?.tennisDark,
      contrastText: theme.colors?.white,
      50: theme.colors?.green50,
      100: theme.colors?.green100,
      200: theme.colors?.green200,
      300: theme.colors?.green300,
      400: theme.colors?.green400,
      500: theme.colors?.green500,
      600: theme.colors?.green600,
      700: theme.colors?.green700,
      800: theme.colors?.green800,
      900: theme.colors?.green900,
      1000: theme.colors?.green1000,
    },
    black: {
      light: theme.colors?.black,
      main: theme.colors?.black,
      dark: theme.colors?.black,
      contrastText: theme.colors?.white,
    },
    white: {
      light: theme.colors?.white,
      main: theme.colors?.white,
      dark: theme.colors?.white,
      contrastText: theme.colors?.black,
    },
    grey: {
      light: theme.colors?.grey50,
      main: theme.colors?.grey100,
      dark: theme.colors?.grey300,
      contrastText: theme.colors?.black,
      50: theme.colors?.grey50,
      // 100: theme.colors?.grey100,
      // 200: theme.colors?.grey200,
      // 300: theme.colors?.grey300,
      // 400: theme.colors?.grey400,
      // 500: theme.darkTextSecondary,
      // 600: theme.heading,
      // 700: theme.darkTextPrimary,
      // 800: theme.colors?.grey800,
      // 900: theme.textDark,
      // 1000: theme.colors?.grey1000,
      100: theme.colors?.grey100,
      200: theme.colors?.grey200,
      300: theme.colors?.grey300,
      400: theme.colors?.grey400,
      500: theme.colors?.grey500,
      600: theme.colors?.grey600,
      700: theme.colors?.grey700,
      800: theme.colors?.grey800,
      900: theme.colors?.grey900,
      1000: theme.colors?.grey1000,
      1100: theme.colors?.grey1100,
      1200: theme.colors?.grey1200,
      1300: theme.colors?.grey1300,
      1400: theme.colors?.grey1400,
    },
    dark: {
      light: theme.colors?.darkTextPrimary,
      main: theme.colors?.darkLevel1,
      dark: theme.colors?.darkLevel2,
      800: theme.colors?.darkBackground,
      900: theme.colors?.darkPaper,
    },
    text: {
      primary: theme.darkTextPrimary,
      secondary: theme.darkTextSecondary,
      dark: theme.textDark,
      hint: theme.colors?.grey100,
      grey: theme.colors?.grey600,
    },
    background: {
      paper: theme.paper,
      default: theme.backgroundDefault,
    },
  };
};

export default palette;
